service: HOTEL-Hakan-Server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: Julia
  region: eu-north-1
  iam:
    role: arn:aws:iam::429799042192:role/events-cloud




plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  getRooms:
    handler: functions/getRooms/index.handler
    events:
      - httpApi:
          path: '/rooms'
          method: GET
  postRooms:
    handler: functions/postRooms/index.handler
    events:
      - httpApi:
          path: '/rooms'
          method: POST
  bookRoom:
    handler: functions/bookRoom/index.handler
    events:
      - httpApi:
          path: '/book'
          method: POST
  availableRoom:
    handler: functions/findavailableRoom/index.handler
    events:
      - httpApi:
          path: '/available'
          method: POST
  getAllBookedRooms:
    handler: functions/getAllBookedRooms/index.handler
    events:
      - httpApi:
          path: /allBookedRooms
          method: GET
  deleteBooking:
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: '/deleteBooking'
          method: POST
  changeBooking:
    handler: functions/changeBooking/index.handler
    events:
      - httpApi:
          path: '/changeBooking'
          method: POST        



resources:
  Resources:
    roomsDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms-db
        AttributeDefinitions:
          - AttributeName: id 
            AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        