service: HOTEL-Hakan-Server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: MarkoRole
  region: eu-north-1
  iam:
    role: arn:aws:iam::228421314153:role/events-practice

plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  getRooms:
    handler: functions/getRooms/index.handler
    events:
      - httpApi:
          path: '/rooms'
          method: GET
  postRooms:
    handler: functions/postRooms/index.handler
    events:
      - httpApi:
          path: '/rooms'
          method: POST
  bookRoom:
    handler: functions/bookRoom/index.handler
    events:
      - httpApi:
          path: '/book'
          method: POST
  availableRoom:
    handler: functions/findavailableRoom/index.handler
    events:
      - httpApi:
          path: '/available'
          method: POST
  getAllBookedRooms:
    handler: functions/getAllBookedRooms/index.handler
    events:
      - httpApi:
          path: /allBookedRooms
          method: GET

resources:
  Resources:
    roomsDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms-db
        AttributeDefinitions:
          - AttributeName: id 
            AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        